// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Fire.h"
#define POWER 0.7
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Fire::Fire(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::feeder.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Fire::Initialize() {
	RobotMap::feederShooterFeedingMotor->Set(0.0);
	printf("Fire initialized \n");
}

// Called repeatedly when this Command is scheduled to run
void Fire::Execute() {

	if(Robot::oi->getLeftStick()->GetRawButton(1)){
		printf("Left button triggered \n");
	}
	if(Robot::oi->getRightStick()->GetRawButton(1)){
		printf("Right button triggered \n");
	}
	//Run the motors, using a current power constant which is found at Robot::shooter->shootPower
	if (Robot::oi->getLeftStick()->GetRawButton(1) && Robot::oi->getRightStick()->GetRawButton(1)){
		printf("Both buttons triggered \n");
		RobotMap::feederShooterFeedingMotor->Set(POWER);
	}
	else{
		RobotMap::feederShooterFeedingMotor->Set(0.0);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool Fire::IsFinished() {
	return false;
    //Check whether both buttons are still pressed.
}

// Called once after isFinished returns true
void Fire::End() {
	//Probably nothing - setting motors to zero would require them to reset
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run b
void Fire::Interrupted() {
	End();
}
