// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"
#include <string>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/Aim.h"
#include "Commands/AimPreset.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DecreaseShooterPower.h"
#include "Commands/Drive.h"
#include "Commands/Fire.h"
#include "Commands/IncreaseShooterPower.h"
#include "Commands/Intake.h"
#include "Commands/RunShooter.h"
#include "Commands/RunWinch.h"
#include "Commands/ShooterPresetPower.h"
#include "Commands/ToggleDrive.h"
#include "Commands/TurnIntakeOff.h"
#include "Commands/TurnShooterOff.h"
#include "Commands/decreaseI.h"
#include "Commands/decreaseP.h"
#include "Commands/increaseI.h"
#include "Commands/increaseP.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

using namespace std;

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    opStick.reset(new Joystick(2));
    
    bumpI.reset(new JoystickButton(opStick.get(), 6));
    bumpI->WhenPressed(new increaseI());
    lowerP.reset(new JoystickButton(opStick.get(), 7));
    lowerP->WhenPressed(new decreaseP());
    lowerI.reset(new JoystickButton(opStick.get(), 8));
    lowerI->WhenPressed(new decreaseI());
    bumpP.reset(new JoystickButton(opStick.get(), 5));
    bumpP->WhenPressed(new increaseP());
    aimPresetButton.reset(new JoystickButton(opStick.get(), 10));
    aimPresetButton->WhenPressed(new AimPreset());
    intakeOn.reset(new JoystickButton(opStick.get(), 10));
    intakeOn->WhenPressed(new Intake());
    intakeOff.reset(new JoystickButton(opStick.get(), 9));
    intakeOff->WhenPressed(new TurnIntakeOff());
    offPower.reset(new JoystickButton(opStick.get(), 1));
    offPower->WhenPressed(new TurnShooterOff());
    presetPower.reset(new JoystickButton(opStick.get(), 3));
    presetPower->WhenPressed(new ShooterPresetPower());
    decreasePower.reset(new JoystickButton(opStick.get(), 2));
    decreasePower->WhenPressed(new DecreaseShooterPower());
    increasePower.reset(new JoystickButton(opStick.get(), 4));
    increasePower->WhenPressed(new IncreaseShooterPower());
    rightStick.reset(new Joystick(1));
    
    rightFireButton.reset(new JoystickButton(rightStick.get(), 1));
    rightFireButton->WhenPressed(new Fire());
    leftStick.reset(new Joystick(0));
    
    leftFireButton.reset(new JoystickButton(leftStick.get(), 1));
    leftFireButton->WhenPressed(new Fire());
    toggleButton.reset(new JoystickButton(leftStick.get(), 2));
    toggleButton->WhenPressed(new ToggleDrive());

    // SmartDashboard Buttons
    SmartDashboard::PutData("Aim", new Aim());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

//These are the SmartDashboard commands to display data on screen.
    SmartDashboard::PutNumber("Shooter Power", RobotMap::shooterShooterMotor->Get());
    SmartDashboard::PutString("Ball Intake Motor", ballIntakeMotor1());
    SmartDashboard::PutString("Hopper Feeder Status", shooterFeeder());
    SmartDashboard::PutString("Shooter Status", shooterMotor());
    SmartDashboard::PutString("Drive Configuration", driveConfig());
}

//The following functions are used to get the status of the subsystems for SmartDashboard

	string OI::ballIntakeMotor1(){
		RobotMap::ballIntakeIntakeMotor->Get();
		if (RobotMap::ballIntakeIntakeMotor > 0){
			return "Is On";
		}else{
			return "Is off";
		}
	}

	string OI::shooterFeeder(){
		RobotMap::feederShooterFeedingMotor->Get();
		if(RobotMap::feederShooterFeedingMotor > 0){
			return "On";
		}else{
			return "Off";
		}
	}

	string OI::shooterMotor(){
		RobotMap::shooterShooterMotor->Get();
		if(RobotMap::shooterShooterMotor > 0){
			return "On";
		}else{
			return "Off";
		}
	}

	string OI::driveConfig(){
		Robot::driveTrain->isSwitched;
		if(Robot::driveTrain->isSwitched == true){
			return "Switched";
		}else{
			return "Default";
		}
	}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getLeftStick() {
   return leftStick;
}

std::shared_ptr<Joystick> OI::getRightStick() {
   return rightStick;
}

std::shared_ptr<Joystick> OI::getOpStick() {
   return opStick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
